name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    env:
      APP_NAME: my-app
      TARGET_ENV: dev
      REGION: eu-central

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run commands
        run: |
          echo "Hello from GitHub Actions"
          date
          uname -a

      - name: Show variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Environment: $TARGET_ENV"
          echo "Region: $REGION" 

      - name: Create runtime info
        run: |
          mkdir -p reports
          echo "APP=$APP_NAME" > reports/runtime-info.txt
          echo "ENV=$TARGET_ENV" >> reports/runtime-info.txt
          echo "REGION=$REGION" >> reports/runtime-info.txt

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: workflow-reports
          path: reports/

      - name: Check Secrets
        env:
          CLOUD_API_TOKEN: ${{ secrets.CLOUD_API_TOKEN }}
          SSH_TARGET: ${{ secrets.SSH_TARGET }}
        run: |
          if [ -z "$CLOUD_API_TOKEN" ]; then
           echo "CLOUD_API_TOKEN: missing"
          else
           echo "CLOUD_API_TOKEN: present"
          fi

           if [ -z "$SSH_TARGET" ]; then
            echo "SSH_TARGET: missing"
           else
            echo "SSH_TARGET: present"
           fi
           
      - name: Select Environment
        run: |
           if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "Production mode"
           else
            echo "ENV=dev" >> $GITHUB_ENV
            echo "Development mode"
           fi

      - name: Load Config
        run: |
           if [ "$ENV" = "prod" ]; then
            FILE="config/prod.env"
           else
            FILE="config/dev.env"
            fi

            echo "Using: $FILE"
            cat $FILE
           
